- README.md
Add link to "How it works" section and link to demo video
> docs(README): Add notes about semantic-release

- .travis.yml
- package-lock.json
- package.json
- validate-commit-msg is deprecated. This also makes it match the other repos
- also add spacing to travis.yml
> chore: use commitlint instead of validate-commit-msg

- package-lock.json
- src/FilledEntity.ts
Converter from FilledEntity[] to FilledEntityMap
> feat: added FromFilledEntities util

- src/UI.ts
Indicates why the session was ended
> feat: sessionendstate enum

- src/ReplayError.ts
Also clean up other replay error names for clarity
> feat: error empty entity

- src/FilledEntity.ts
added tomemory util as used in multiple places in ui and sdk
> feat: tomemory

- src/FilledEntity.ts
- src/UI.ts
> fix: clean-up dummy entities

- src/FilledEntity.ts
- src/LogDialog.ts
- src/ModelUtils.ts
- src/TrainDialog.ts
- src/modelUtils.test.ts
Store logic result filled entities in logic result so can show on replay
> feat: logic result entities

- package-lock.json
- src/ReplayError.ts
> feat: add replay exception

- package-lock.json
- src/FilledEntity.ts
> fix: rename valueasprebuilt

- src/FilledEntity.ts
- src/filledEntity.test.ts
Flip entity based map to id based map
> feat: entitymaptoidmap

- .circleci/config.yml
Seems there is some glitch with CircleCI it never detected my other PR / branch #185 so copying here.
I wonder if it has to due with using a period in the branch name which confused it.
>  build: update circleci config to 2.1

- src/Action.ts
- src/ReplayError.ts
Changes for https://github.com/microsoft/ConversationLearner-UI/pull/1256 and https://github.com/microsoft/ConversationLearner-SDK/pull/493
> feat: add DISPATCH action type

- .vscode/launch.json
- package.json
- remove rimraf to avoid breaking links
https://github.com/Microsoft/TypeScript/issues/16057#issuecomment-344262121
- remove broken launch config
> Remove rimraf and launch config

- src/ObiUtils.test.ts
(Essentially) no-op change to force release and npm build
> style: force release

- src/Callback.ts
- src/ObiUtils.test.ts
Looks like `style:` doesn't trigger a release ?
> fix: really really force release

- src/Callback.ts
- src/ObiUtils.test.ts
- src/ObiUtils.ts
Rename parseLGString to addToLGMap
> fix: refactor parseLGString/addToLGMap

- .vscode/settings.json
- src/Teach.ts
- src/Transcript.ts
Related to https://github.com/microsoft/ConversationLearner-UI/pull/1297
> fix: rename history to activities

- src/Entity.ts
^^ -- didn't see a constant for this anywhere else
> fix: add constant for max enum value length

- src/Action.ts
- src/FilledEntity.ts
- src/Memory.ts
Needed for https://github.com/microsoft/ConversationLearner-UI/pull/1332
Adds ability to specify constant number value for ValueConditions and adds new operators.
>  feat: add support for more complex conditions

- src/Entity.ts
Verbosify constant names per comments in https://github.com/microsoft/ConversationLearner-Models/pull/212
> fix: update constant names for enum values

- .github/workflows/build.yml
- .travis.yml
Testing out conditional syntax for steps based on suggestions from support engineer
> build: test if conditional syntax

- .github/workflows/build.yml
add `closed` type to pull_request event triggers
> fix: trigger on closed

- src/Action.ts
- src/ReplayError.ts
Consolidates functionality of DispatchActions and ChangeModel actions to ModelActions which store info about model.
> feat: add "Change Model" type

- src/Entity.ts
> feat: add a constant for max model name length

- src/LogDialog.ts
Moved logQueryResult to models
> feat: log query result
